const equipment = [
  {
    id: 1,
    code: "FIN-RIE-0001",
    name: "Bomba de riego principal",
    finca: "Finca Norte",
    category: "Riego",
    status: "OPERATIVO",
    lastMaintenance: "2024-11-15",
    critical: "Impulsor, sello",
    notes: "Operando estable"
  },
  {
    id: 2,
    code: "FIN-TRAC-0002",
    name: "Tractor John Deere",
    finca: "Finca Central",
    category: "Vehículo",
    status: "OPERATIVO",
    lastMaintenance: "2024-10-20",
    critical: "Batería, filtro de combustible",
    notes: "Disponible para labores pesadas"
  },
  {
    id: 3,
    code: "FIN-GEN-0003",
    name: "Generador emergencia",
    finca: "Finca Sur",
    category: "Energía",
    status: "FUERA_DE_SERVICIO",
    lastMaintenance: "2024-09-10",
    critical: "Arrancador, filtros",
    notes: "En diagnóstico de tablero"
  }
];

const inventory = [
  { code: "REP-001", name: "Filtro aceite", finca: "Finca Norte", category: "Filtros", stock: 12, critical: true },
  { code: "REP-002", name: "Banda trasportadora", finca: "Finca Central", category: "Bandas", stock: 4, critical: true },
  { code: "REP-003", name: "Lubricante 15w40", finca: "Finca Sur", category: "Lubricantes", stock: 20, critical: false },
  { code: "REP-004", name: "Bujía", finca: "Finca Norte", category: "Encendido", stock: 30, critical: false }
];

let tasks = [
  {
    id: crypto.randomUUID(),
    date: new Date().toISOString().slice(0, 10),
    equipmentId: 1,
    type: "Preventivo",
    description: "Revisión semanal de sello",
    status: "Planificado",
    cost: 0,
    notes: "",
    autoGenerated: true
  }
];

let maintenanceRecords = [
  { id: crypto.randomUUID(), equipmentId: 1, type: "Correctivo", responsible: "Luis R.", parts: "Sello", cost: 250, date: "2024-11-05" },
  { id: crypto.randomUUID(), equipmentId: 2, type: "Preventivo", responsible: "Carla D.", parts: "Filtro", cost: 80, date: "2024-10-21" },
  { id: crypto.randomUUID(), equipmentId: 3, type: "Inspección", responsible: "Equipo eléctrico", parts: "", cost: 0, date: "2024-09-12" }
];

let staff = [
  { name: "Luis R.", specialty: "Mecánico", contact: "3101234567", status: "Disponible" },
  { name: "Carla D.", specialty: "Planificadora", contact: "carla@valleflor.com", status: "Ocupado" },
  { name: "Orlando P.", specialty: "Electricista", contact: "3117654321", status: "Disponible" }
];

const state = {
  filters: {
    finca: "Todos",
    category: "Todos",
    year: "Todos",
    type: "Todos"
  }
};

const qs = (sel) => document.querySelector(sel);
const qsa = (sel) => Array.from(document.querySelectorAll(sel));

function initFilters() {
  const fincas = ["Todos", ...new Set(equipment.map((e) => e.finca))];
  const categories = ["Todos", ...new Set(equipment.map((e) => e.category))];
  const years = ["Todos", ...new Set(maintenanceRecords.map((r) => new Date(r.date).getFullYear()))];
  const types = ["Todos", "Preventivo", "Correctivo", "Predictivo", "Inspección", "Calibración"];

  fillSelect("dashboardFincaFilter", fincas);
  fillSelect("dashboardCategoryFilter", categories);
  fillSelect("dashboardYearFilter", years);
  fillSelect("dashboardTypeFilter", types);
  fillSelect("taskEquipment", equipment.map((e) => ({ label: `${e.code} - ${e.name}`, value: e.id })));
  fillSelect("lifeFinca", fincas.filter((f) => f !== "Todos"));
  fillSelect("lifeEquipment", equipment.map((e) => ({ label: e.code, value: e.id })));
  fillSelect("planningMonth", generateMonths(), true);
}

function fillSelect(id, values, isMonth = false) {
  const el = qs(`#${id}`);
  el.innerHTML = "";
  values.forEach((val) => {
    const option = document.createElement("option");
    option.value = isMonth ? val.value : typeof val === "object" ? val.value : val;
    option.textContent = typeof val === "object" ? val.label : val;
    el.appendChild(option);
  });
}

function generateMonths() {
  const months = [];
  const today = new Date();
  for (let i = 0; i < 12; i++) {
    const date = new Date(today.getFullYear(), today.getMonth() + i, 1);
    const iso = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`;
    months.push({ label: date.toLocaleString("es", { month: "long", year: "numeric" }), value: iso });
  }
  return months;
}

function renderKPIs() {
  const filtered = filterRecords();
  const kpis = [
    { label: "Equipos", value: equipment.length },
    { label: "Operativos", value: equipment.filter((e) => e.status === "OPERATIVO").length },
    { label: "Tareas planificadas", value: tasks.length },
    { label: "Mantenimientos registrados", value: maintenanceRecords.length }
  ];
  qs("#kpiGrid").innerHTML = kpis
    .map((k) => `<div class="kpi"><span>${k.label}</span><strong>${k.value}</strong></div>`) 
    .join("");

  renderCharts(filtered);
  renderSummaryByFinca(filtered);
}

function filterRecords() {
  return maintenanceRecords.filter((r) => {
    const matchesFinca = state.filters.finca === "Todos" || equipment.find((e) => e.id === r.equipmentId)?.finca === state.filters.finca;
    const matchesCategory = state.filters.category === "Todos" || equipment.find((e) => e.id === r.equipmentId)?.category === state.filters.category;
    const matchesYear = state.filters.year === "Todos" || new Date(r.date).getFullYear().toString() === state.filters.year.toString();
    const matchesType = state.filters.type === "Todos" || r.type === state.filters.type;
    return matchesFinca && matchesCategory && matchesYear && matchesType;
  });
}

function renderCharts(records) {
  const countsByType = records.reduce((acc, r) => {
    acc[r.type] = (acc[r.type] || 0) + 1;
    return acc;
  }, {});
  const chartArea = qs("#taskChart");
  chartArea.innerHTML = `<h3>Gráfico por tipo</h3><div class="bars">${Object.entries(countsByType)
    .map(([t, c]) => `<div class="bar" style="height:${30 + c * 15}px"><span>${t}</span><strong>${c}</strong></div>`)
    .join("")}</div>`;

  const costsByMonth = records.reduce((acc, r) => {
    const key = `${new Date(r.date).getFullYear()}-${String(new Date(r.date).getMonth() + 1).padStart(2, "0")}`;
    acc[key] = (acc[key] || 0) + Number(r.cost || 0);
    return acc;
  }, {});
  const costChart = qs("#costChart");
  costChart.innerHTML = `<h3>Costos por mes</h3><div class="bars">${Object.entries(costsByMonth)
    .map(([m, c]) => `<div class="bar bar-secondary" style="height:${30 + c / 10}px"><span>${m}</span><strong>$${c.toFixed(0)}</strong></div>`)
    .join("")}</div>`;
}

function renderSummaryByFinca(records) {
  const grouped = records.reduce((acc, r) => {
    const eq = equipment.find((e) => e.id === r.equipmentId);
    if (!eq) return acc;
    const key = eq.finca;
    if (!acc[key]) acc[key] = { count: 0, cost: 0 };
    acc[key].count += 1;
    acc[key].cost += Number(r.cost || 0);
    return acc;
  }, {});

  qs("#summaryByFinca").innerHTML = Object.entries(grouped)
    .map(
      ([finca, data]) => `
      <div class="summary-card">
        <h3>${finca}</h3>
        <p>${data.count} mantenimientos</p>
        <p>Costos: $${data.cost.toFixed(0)}</p>
      </div>
    `
    )
    .join("") || "<p>Sin datos filtrados</p>";
}

function renderCalendar(monthValue) {
  const calendar = qs("#calendar");
  const [year, month] = monthValue ? monthValue.split("-") : new Date().toISOString().split("-");
  const firstDay = new Date(Number(year), Number(month) - 1, 1);
  const daysInMonth = new Date(Number(year), Number(month), 0).getDate();
  const startDay = firstDay.getDay();
  const labels = ["Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"];

  const monthTasks = tasks.filter((t) => new Date(t.date).getMonth() + 1 === Number(month) && new Date(t.date).getFullYear() === Number(year));

  calendar.innerHTML = `
    <div class="calendar-header">
      <div class="badge">${firstDay.toLocaleString("es", { month: "long", year: "numeric" })}</div>
      <div style="text-align:right;color:var(--muted)">Tareas visibles en la cuadrícula</div>
    </div>
    <div class="calendar-weekdays">${labels.map((d) => `<div class="muted">${d}</div>`).join("")}</div>
    <div class="calendar-days"></div>
  `;

  const daysContainer = calendar.querySelector(".calendar-days");
  for (let i = 0; i < startDay; i++) {
    daysContainer.appendChild(document.createElement("div"));
  }
  for (let day = 1; day <= daysInMonth; day++) {
    const dateStr = `${year}-${String(month).padStart(2, "0")}-${String(day).padStart(2, "0")}`;
    const cell = document.createElement("div");
    cell.className = "calendar-day";
    const dayTasks = monthTasks.filter((t) => t.date === dateStr);
    cell.innerHTML = `<div class="date">${day}</div>${dayTasks
      .map((t) => `<div class="chip ${t.type.toLowerCase()}">${t.type} - ${equipment.find((e) => e.id === t.equipmentId)?.code || ""}</div>`)
      .join("")}`;
    cell.addEventListener("click", () => {
      qs("#taskDate").value = dateStr;
      qs("#taskDescription").focus();
    });
    daysContainer.appendChild(cell);
  }
}

function handleTaskSubmit(e) {
  e.preventDefault();
  const payload = {
    id: crypto.randomUUID(),
    date: qs("#taskDate").value,
    equipmentId: Number(qs("#taskEquipment").value),
    type: qs("#taskType").value,
    description: qs("#taskDescription").value,
    status: qs("#taskStatus").value,
    cost: Number(qs("#taskCost").value || 0),
    notes: qs("#taskNotes").value,
    autoGenerated: false
  };
  tasks.push(payload);
  if (payload.status === "Completado" && payload.cost > 0) {
    maintenanceRecords.push({
      id: crypto.randomUUID(),
      equipmentId: payload.equipmentId,
      type: payload.type,
      responsible: "Equipo en campo",
      parts: payload.notes,
      cost: payload.cost,
      date: payload.date
    });
  }
  qs("#taskFeedback").textContent = `Tarea guardada para ${payload.date}`;
  renderCalendar(qs("#planningMonth").value);
  renderKPIs();
  renderRecentMaintenance();
  renderLife();
}

function renderEquipment() {
  const tbody = qs("#equipmentTable");
  tbody.innerHTML = equipment
    .map(
      (e) => `
      <tr>
        <td>${e.code}</td>
        <td>${e.name}</td>
        <td>${e.finca}</td>
        <td>${e.category}</td>
        <td>${renderStatusBadge(e.status)}</td>
        <td>${e.lastMaintenance}</td>
        <td>
          <select data-id="${e.id}" class="equipment-status">
            <option value="OPERATIVO" ${e.status === "OPERATIVO" ? "selected" : ""}>OPERATIVO</option>
            <option value="FUERA_DE_SERVICIO" ${e.status === "FUERA_DE_SERVICIO" ? "selected" : ""}>FUERA DE SERVICIO</option>
          </select>
        </td>
      </tr>
    `
    )
    .join("");
  qsa(".equipment-status").forEach((sel) => sel.addEventListener("change", onEquipmentStatusChange));
}

function renderStatusBadge(status) {
  const text = status === "OPERATIVO" ? "Operativo" : "Fuera de servicio";
  const color = status === "OPERATIVO" ? "badge" : "chip corrective";
  return `<span class="${color}">${text}</span>`;
}

function onEquipmentStatusChange(ev) {
  const id = Number(ev.target.dataset.id);
  const value = ev.target.value;
  const eq = equipment.find((e) => e.id === id);
  if (!eq) return;
  eq.status = value;
  if (value !== "OPERATIVO") {
    const today = new Date().toISOString().slice(0, 10);
    tasks = tasks.filter((t) => !(t.equipmentId === id && t.date > today && t.autoGenerated));
  } else {
    generatePreventiveTasksFor(id);
  }
  renderCalendar(qs("#planningMonth").value);
  renderKPIs();
}

function registerEquipment(e) {
  e.preventDefault();
  const newId = Math.max(...equipment.map((eq) => eq.id)) + 1;
  const category = qs("#equipmentCategory").value;
  const code = `FIN-${category.substring(0, 3).toUpperCase()}-${String(newId).padStart(4, "0")}`;
  const entry = {
    id: newId,
    code,
    name: qs("#equipmentName").value,
    finca: qs("#equipmentFinca").value,
    category,
    status: qs("#equipmentStatus").value,
    lastMaintenance: qs("#equipmentLastMaintenance").value,
    critical: qs("#equipmentCritical").value,
    notes: qs("#equipmentNotes").value
  };
  equipment.push(entry);
  initFilters();
  renderEquipment();
  generatePreventiveTasksFor(entry.id);
  renderCalendar(qs("#planningMonth").value);
}

function renderInventory() {
  const categoryFilter = qs("#inventoryCategory").value.toLowerCase();
  const fincaFilter = qs("#inventoryFinca").value.toLowerCase();
  const searchValue = qs("#inventorySearch").value.toLowerCase();

  const filtered = inventory.filter((item) => {
    const matchesCategory = !categoryFilter || item.category.toLowerCase().includes(categoryFilter);
    const matchesFinca = !fincaFilter || item.finca.toLowerCase().includes(fincaFilter);
    const matchesSearch = !searchValue || item.code.toLowerCase().includes(searchValue);
    return matchesCategory && matchesFinca && matchesSearch;
  });

  const tbody = qs("#inventoryTable");
  tbody.innerHTML = filtered
    .map(
      (item) => `<tr><td>${item.code}</td><td>${item.name}</td><td>${item.finca}</td><td>${item.category}</td><td>${item.stock}</td><td>${item.critical ? "Sí" : "No"}</td></tr>`
    )
    .join("");

  const datalist = qs("#inventorySearchOptions");
  datalist.innerHTML = inventory
    .map((i) => `<option value="${i.code}">${i.code} – ${i.name}</option>`)
    .join("");
}

function exportInventory() {
  const rows = [["Código", "Nombre", "Finca", "Categoría", "Stock", "Crítico"], ...inventory.map((i) => [i.code, i.name, i.finca, i.category, i.stock, i.critical ? "Sí" : "No"])];
  const csv = rows.map((r) => r.join(",")).join("\n");
  const blob = new Blob([csv], { type: "text/csv" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "inventario-valleflor.csv";
  a.click();
  URL.revokeObjectURL(url);
}

function registerMaintenance(e) {
  e.preventDefault();
  const code = qs("#maintenanceEquipment").value;
  const eq = equipment.find((e) => e.code === code);
  if (!eq) return alert("Seleccione un equipo válido");
  const record = {
    id: crypto.randomUUID(),
    equipmentId: eq.id,
    type: qs("#maintenanceType").value,
    responsible: qs("#maintenanceResponsible").value,
    parts: qs("#maintenanceParts").value,
    cost: Number(qs("#maintenanceCost").value || 0),
    date: qs("#maintenanceDate").value
  };
  maintenanceRecords.unshift(record);
  eq.lastMaintenance = record.date;
  renderKPIs();
  renderRecentMaintenance();
  renderLife();
}

function renderRecentMaintenance() {
  const container = qs("#recentMaintenance");
  container.innerHTML = maintenanceRecords
    .slice(0, 5)
    .map((r) => {
      const eq = equipment.find((e) => e.id === r.equipmentId);
      return `<div class="summary-card">
        <h3>${eq?.code || "Equipo"} - ${r.type}</h3>
        <p>${r.date} | ${r.responsible}</p>
        <p>Repuestos: ${r.parts || "N/A"} | Costo: $${r.cost}</p>
      </div>`;
    })
    .join("");
}

function renderLife() {
  const finca = qs("#lifeFinca").value;
  const equipmentId = Number(qs("#lifeEquipment").value) || equipment[0].id;
  const eq = equipment.find((e) => e.id === equipmentId && (!finca || e.finca === finca));
  if (!eq) return;
  qs("#lifeEquipment").value = eq.id;
  qs("#lifeCard").innerHTML = `
    <h3>${eq.name}</h3>
    <p><strong>Código:</strong> ${eq.code}</p>
    <p><strong>Finca:</strong> ${eq.finca}</p>
    <p><strong>Categoría:</strong> ${eq.category}</p>
    <p><strong>Último mantenimiento:</strong> ${eq.lastMaintenance}</p>
    <p><strong>Repuestos críticos:</strong> ${eq.critical}</p>
    <p><strong>Observaciones:</strong> ${eq.notes}</p>
    <span class="${eq.status === "OPERATIVO" ? "badge" : "chip corrective"}">${eq.status.replace("_", " ")}</span>
  `;

  const history = maintenanceRecords.filter((r) => r.equipmentId === eq.id);
  qs("#lifeTable").innerHTML = history
    .map((r) => `<tr><td>${r.date}</td><td>${r.type}</td><td>${r.responsible}</td><td>$${r.cost}</td></tr>`)
    .join("");

  const grouped = history.reduce((acc, r) => {
    const key = `${new Date(r.date).getMonth() + 1}/${new Date(r.date).getFullYear()}`;
    acc[key] = (acc[key] || 0) + 1;
    return acc;
  }, {});
  qs("#lifeChart").innerHTML = `<div class="bars">${Object.entries(grouped)
    .map(([k, v]) => `<div class="bar" style="height:${25 + v * 18}px"><span>${k}</span><strong>${v}</strong></div>`)
    .join("")}</div>`;
}

function registerStaff(e) {
  e.preventDefault();
  staff.push({
    name: qs("#staffName").value,
    specialty: qs("#staffSpecialty").value,
    contact: qs("#staffContact").value,
    status: qs("#staffStatus").value
  });
  renderStaff();
}

function renderStaff() {
  qs("#staffTable").innerHTML = staff
    .map((p) => `<tr><td>${p.name}</td><td>${p.specialty}</td><td>${p.contact}</td><td>${p.status}</td></tr>`)
    .join("");
}

function generatePreventiveTasksFor(equipmentId) {
  const eq = equipment.find((e) => e.id === equipmentId);
  if (!eq || eq.status !== "OPERATIVO") return;
  const lastDate = new Date(eq.lastMaintenance);
  for (let i = 1; i <= 12; i++) {
    const next = new Date(lastDate.getFullYear(), lastDate.getMonth() + i, lastDate.getDate());
    let day = next.getDay();
    if (day === 0) next.setDate(next.getDate() + 1);
    if (day === 6) next.setDate(next.getDate() + 2);
    const dateStr = next.toISOString().slice(0, 10);
    if (!tasks.some((t) => t.equipmentId === eq.id && t.date === dateStr && t.autoGenerated)) {
      tasks.push({
        id: crypto.randomUUID(),
        date: dateStr,
        equipmentId: eq.id,
        type: "Preventivo",
        description: "Preventivo mensual",
        status: "Planificado",
        cost: 0,
        notes: "Generado automáticamente",
        autoGenerated: true
      });
    }
  }
}

function regeneratePreventives() {
  tasks = tasks.filter((t) => !t.autoGenerated);
  equipment.forEach((eq) => generatePreventiveTasksFor(eq.id));
  renderCalendar(qs("#planningMonth").value);
}

function renderDashboardOptionsListeners() {
  ["dashboardFincaFilter", "dashboardCategoryFilter", "dashboardYearFilter", "dashboardTypeFilter"].forEach((id) => {
    qs(`#${id}`).addEventListener("change", (e) => {
      state.filters = { ...state.filters, [id.replace("dashboard", "").replace("Filter", "").toLowerCase()]: e.target.value };
      renderKPIs();
    });
  });
}

function renderInventoryListeners() {
  ["inventoryCategory", "inventoryFinca", "inventorySearch"].forEach((id) => {
    qs(`#${id}`).addEventListener("input", renderInventory);
  });
  qs("#inventoryExport").addEventListener("click", exportInventory);
}

function renderPlanningListeners() {
  qs("#taskForm").addEventListener("submit", handleTaskSubmit);
  qs("#planningMonth").addEventListener("change", (e) => renderCalendar(e.target.value));
  qs("#generatePreventive").addEventListener("click", regeneratePreventives);
}

function renderLifeListeners() {
  ["lifeFinca", "lifeEquipment"].forEach((id) => qs(`#${id}`).addEventListener("change", renderLife));
}

function renderMaintenanceListeners() {
  qs("#maintenanceForm").addEventListener("submit", registerMaintenance);
}

function renderStaffListeners() {
  qs("#staffForm").addEventListener("submit", registerStaff);
}

function renderInventorySearchLabels() {
  qs("#equipmentOptions").innerHTML = equipment.map((e) => `<option value="${e.code}">${e.code} - ${e.name}</option>`).join("");
}

function boot() {
  initFilters();
  renderDashboardOptionsListeners();
  renderPlanningListeners();
  renderInventoryListeners();
  renderLifeListeners();
  renderMaintenanceListeners();
  renderStaffListeners();

  renderKPIs();
  renderCalendar(qs("#planningMonth").value);
  renderEquipment();
  renderInventory();
  renderRecentMaintenance();
  renderLife();
  renderStaff();
  renderInventorySearchLabels();
}

boot();
